export const GET_LOGIN_EXERCISES_REQUEST = 'GET_LOGIN_EXERCISES_REQUEST'
export const GET_LOGIN_EXERCISES_SUCCESS = 'GET_LOGIN_EXERCISES_SUCCESS'
export const GET_LOGIN_EXERCISES_FAIL = 'GET_LOGIN_EXERCISES_FAIL'
export const GET_LOGIN_EXERCISES_RESET = 'GET_LOGIN_EXERCISES_RESET'

export const EXERCISES_BY_FILTERS_REQUEST = 'EXERCISES_BY_FILTERS_REQUEST'
export const EXERCISES_BY_FILTERS_SUCCESS = 'EXERCISES_BY_FILTERS_SUCCESS'
export const EXERCISES_BY_FILTERS_FAIL = 'EXERCISES_BY_FILTERS_FAIL'
export const EXERCISES_BY_FILTERS_RESET = 'EXERCISES_BY_FILTERS_RESET'

export const EXERCISE_BY_ID_REQUEST = 'EXERCISE_BY_ID_REQUEST'
export const EXERCISE_BY_ID_SUCCESS = 'EXERCISE_BY_ID_SUCCESS'
export const EXERCISE_BY_ID_FAIL = 'EXERCISE_BY_ID_FAIL'
export const EXERCISE_BY_ID_RESET = 'EXERCISE_BY_ID_RESET'
