export const GET_LOGIN_NEWS_REQUEST = 'GET_LOGIN_NEWS_REQUEST'
export const GET_LOGIN_NEWS_SUCCESS = 'GET_LOGIN_NEWS_SUCCESS'
export const GET_LOGIN_NEWS_FAIL = 'GET_LOGIN_NEWS_FAIL'
export const GET_LOGIN_NEWS_RESET = 'GET_LOGIN_NEWS_RESET'
