export const GET_USER_LOGIN_REQUEST = 'GET_USER_LOGIN_REQUEST'
export const GET_USER_LOGIN_SUCCESS = 'GET_USER_LOGIN_SUCCESS'
export const GET_USER_LOGIN_FAIL = 'GET_USER_LOGIN_FAIL'
export const GET_USER_LOGOUT = 'GET_USER_LOGOUT'

export const USER_REFRESH_TOKEN_REQUEST = 'USER_REFRESH_TOKEN_REQUEST'
export const USER_REFRESH_TOKEN_SUCCESS = 'USER_REFRESH_TOKEN_SUCCESS'
export const USER_REFRESH_TOKEN_FAIL = 'USER_REFRESH_TOKEN_FAIL'
export const USER_REFRESH_TOKEN_RESET = 'USER_REFRESH_TOKEN_RESET'

export const GOOGLE_AUTH_REQUEST = 'GOOGLE_AUTH_REQUEST'
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS'
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL'
export const GOOGLE_AUTH_RESET = 'GOOGLE_AUTH_RESET'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET'

export const AVATAR_UPDATE_REQUEST = 'AVATAR_UPDATE_REQUEST'
export const AVATAR_UPDATE_SUCCESS = 'AVATAR_UPDATE_SUCCESS'
export const AVATAR_UPDATE_FAIL = 'AVATAR_UPDATE_FAIL'
export const AVATAR_UPDATE_RESET = 'AVATAR_UPDATE_RESET'
