export const GET_USER_LOGIN_REQUEST = 'GET_USER_LOGIN_REQUEST'
export const GET_USER_LOGIN_SUCCESS = 'GET_USER_LOGIN_SUCCESS'
export const GET_USER_LOGIN_FAIL = 'GET_USER_LOGIN_FAIL'
export const GET_USER_LOGOUT = 'GET_USER_LOGOUT'

export const USER_REFRESH_TOKEN_REQUEST = 'USER_REFRESH_TOKEN_REQUEST'
export const USER_REFRESH_TOKEN_SUCCESS = 'USER_REFRESH_TOKEN_SUCCESS'
export const USER_REFRESH_TOKEN_FAIL = 'USER_REFRESH_TOKEN_FAIL'
export const USER_REFRESH_TOKEN_RESET = 'USER_REFRESH_TOKEN_RESET'

export const GET_USER_LOGIN_BY_GOOGLE_REQUEST =
  'GET_USER_LOGIN_BY_GOOGLE_REQUEST'
export const GET_USER_LOGIN_BY_GOOGLE_UCCESS =
  'GET_USER_LOGIN_BY_GOOGLE_SUCCESS'
export const GET_USER_LOGIN_BY_GOOGLE_FAIL = 'GET_USER_LOGIN_BY_GOOGLE_FAIL'
export const GET_USER_LOGIN_BY_GOOGLE_RESET = 'GET_USER_LOGIN_BY_GOOGLE_RESET'
